	[font]
	normal      = {family = "Iosevka Nerd Font", style = "normal"}
	bold        = {family = "Iosevka Nerd Font", style = "bold"}
	italic 	    = {family = "Iosevka Nerd Font", style = "italic"}
	bold_italic = {family = "Iosevka Nerd Font", style = "bold_italic"}

	size = 15

